name: BetterTablist
version: 1.0
main: org.felixstaude.tablist.core.TablistCustomizer
api-version: 1.20
author: felixstaude
softdepend: [PlaceholderAPI]

commands:
  tablistreload:
    description: Reloads the tablist plugin config
    usage: /<command>
    permission: tablist.reload

permissions:
  tablist.reload:
    description: Allows reloading of the tablist config
    default: op
